{% set version = "1.0.1" %}

package:
  name: glue-core
  version: {{version}}

source:

  fn: glue-core-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glue-core/glue-core-{{version}}.tar.gz
  sha256: 32e7f3742bc944d0012766945eb5950ec49845c464227f34e56a380d07371fca

build:
  number: 0
  skip: True  # [ppc64le]
  skip: True  # [py<36]
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - glue = glue.main:main
    - glue-config = glue.config_gen:main
    - glue-deps = glue._deps:main
  osx_is_app: True
  ignore_run_exports:
    - pyqt

requirements:

  host:
    - python
    - pip
    # We need to include PyQt5 here to make sure that PyQt5 doesn't
    # get included in install_requires
    - pyqt >=5.6
    - setuptools_scm

  run:

    # The following is needed to make sure that the package works as a GUI
    # application (glue needs to be run with python.app, not python)
    - python.app  # [osx]

    # Required dependencies
    - python
    - numpy >=1.16
    - pandas >=1.0
    - astropy >=4.0
    - matplotlib >=3.2
    - qtpy >=1.9
    - ipython >=4.0
    - ipykernel >=4.0,!=5.0.0,!=5.1.0
    - qtconsole >=4.3
    - dill >=0.2
    - xlrd >=1.2
    - h5py >=2.10
    - bottleneck >=1.2
    - mpl-scatter-density >=0.7
    - setuptools >=30.3.0
    - echo >=0.5
    - scipy >=1.0
    - jupyter_client <7


    # Optional dependencies (defined in ``extras_require``)
    - scikit-image

    # Temporary: the scikit-image conda package is missing the dask dependency
    # so we add it here for now
    - dask

test:
  imports:
    - glue
    - glue.core
    - glue.app.qt
  commands:
    - glue --version
    - glue-deps list

# NOTE: we deliberatey do NOT include an app entry here, because we instead do this
# in the glueviz meta-package (we don't want glue to appear twice in the navigator)

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration
  dev_url: https://github.com/glue-viz/glue
  doc_url: http://glueviz.rtfd.io

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
