{% set name = "glue-core" %}
{% set version = "1.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: c0359f84417bc869f2c91fe7baa0f50e62061036e995455bca58b449f931bf72

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - glue-config = glue.config_gen:main
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools >=61.2
    - wheel
    - setuptools-scm
  run:
    - python
    - numpy >=1.17
    - matplotlib-base >=3.2
    - scipy >=1.1
    - pandas >=1.2
    - echo >=0.12
    - astropy >=4.0
    - fast-histogram >=0.12
    - ipython >=4.0
    - dill >=0.2
    - h5py >=2.10
    - xlrd >=1.2
    - openpyxl >=3.0
    - mpl-scatter-density >=0.8
    - shapely >=2.0
    # recommended
    - scikit-image
  run_constrained:
    # See https://github.com/python-pillow/Pillow/issues/4509
    # for why we exclude pillow 7.1.0
    - pillow !=7.1.0

test:
  imports:
    - glue
    - glue._plugin_helpers
    - glue._settings_helpers
    - glue.backends
    - glue.config
    - glue.core
    - glue.core.application_base
    - glue.core.callback_property
    - glue.core.command
    - glue.core.component
    - glue.core.component_id
    - glue.core.component_link
    - glue.core.contracts
    - glue.core.coordinate_helpers
    - glue.core.coordinates
    - glue.core.data
    - glue.core.data_collection
    - glue.core.data_combo_helper
    - glue.core.data_derived
    - glue.core.data_factories
    - glue.core.data_factories.fits
    - glue.core.data_factories.hdf5
    - glue.core.data_factories.helpers
    - glue.core.data_factories.pandas
    - glue.core.data_region
    - glue.core.decorators
    - glue.core.edit_subset_mode
    - glue.core.exceptions
    - glue.core.fixed_resolution_buffer
    - glue.core.hub
    - glue.core.hub_callback_container
    - glue.core.joins
    - glue.core.layer_artist
    - glue.core.link_helpers
    - glue.core.link_manager
    - glue.core.message
    - glue.core.registry
    - glue.core.roi
    - glue.core.roi_pretransforms
    - glue.core.session
    - glue.core.simpleforms
    - glue.core.state
    - glue.core.state_objects
    - glue.core.subset
    - glue.core.subset_group
    - glue.core.tests.test_application_base
    - glue.core.tests.test_link_helpers
    - glue.core.tests.test_state
    - glue.core.units
    - glue.core.util
    - glue.core.visual
  commands:
    - pip check
    - pytest --pyargs glue.tests
  requires:
    - pip
    - pytest

about:
  home: https://glueviz.org
  summary: Multi-dimensional linked data exploration
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: Glue is a python project to link visualizations of scientific datasets across many files.
  dev_url: https://github.com/glue-viz/glue
  doc_url: https://docs.glueviz.org

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
