travis:
  secure:
    BINSTAR_TOKEN: CAqFF2Vuq7KaLIYPqbLkmsw2sWB2uWI972dDxo2CmbGmgSo/dvlvPJ2UgPCb4w4/fJLh327OOn8Q8DNGyHh2O7g8n9ercyjDpiTuAVUcM5XaoK2sqIYjm83ukV8fAox4LFFbDMZwiK4IDkZ6v2eZ8Rt8u/wXs+uUF46eAKW3dN91l+cLfYGFOjIjwNzgZvStJkbRb82qD1nfuNYbQuHt7/LLPpRPQRXt6hKL9BHNVsKlPaQDJE9/JZvxCxSx5vmTWzX9gKCDtZGhYAuFIpi75RnfLQNGdotoNRx/ya7iC0iw63NWeYbLGHbj1/lEGiE7WGB2Wd2bl9g8A4v5IgkBIQPEHYhqCA64iDNYb/T+lvGOkLo0kcZc5sfqRXwl4uI/cOzxJ4bPGqDuIkTdLvFyQhVpXt69Pwlv0HesqvZ8ZylEkUhB9q1rlk6OeVqLSYjTMuLyRGz8IoPH3BKCx7iUimz33UAlgZ2vvJAoJzkHUqclcSK9Xptjq17rCpYlW18qpmctljsq4OF1oBj7fTzj3Phu4LR8aoXsGxNrK0lzMRPU8wgzgwohaBRqPmYW+ma6Q5w4vttOoBk1uKBpfD+pQWMxDZDPCKHSfCOrSR8B+9MxxgynKhKvkVSvWcoPWH0fyMMuxwZ1zlMzOA/bO+1GorrKZzOIZF+jiNGUoJPf7Zc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
